[platformio]
default_envs = m5stack-sticks3

[env:m5stack-sticks3]
platform = espressif32
board = m5stack-sticks3
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    m5stack/M5Unified
    https://github.com/T-vK/ESP32-BLE-Mouse.git
build_flags =
    -DCORE_DEBUG_LEVEL=0

[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    m5stack/M5Unified
    https://github.com/T-vK/ESP32-BLE-Mouse.git
build_flags =
    -DCORE_DEBUG_LEVEL=0

[env:m5stack-core-s3]
platform = espressif32
board = m5stack-core-s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    m5stack/M5Unified
    https://github.com/T-vK/ESP32-BLE-Mouse.git
build_flags =
    -DCORE_DEBUG_LEVEL=0
