[platformio]
default_envs = m5stack-cores3

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified
    https://github.com/T-vK/ESP32-BLE-Mouse.git
build_flags =
    -DCORE_DEBUG_LEVEL=0

[env:m5stack-sticks3]
board = m5stack-sticks3
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
upload_speed = 921600
build_flags =
    ${env.build_flags}
    -DTARGET_M5STICKS3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

[env:m5stack-cores3]
board = m5stack-cores3
upload_speed = 1500000
build_flags =
    ${env.build_flags}
    -DTARGET_M5STACK_CORES3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
